// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://esvpnifuizafgdxfnwfl.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVzdnBuaWZ1aXphZmdkeGZud2ZsIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDY3NzIxMzIsImV4cCI6MjA2MjM0ODEzMn0.hii5oaTjxRtdbEsmzmWFfM-BErDfh7SkdMkxOiM7WUs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);